name: UPM on npmjs.com
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  publish:
    strategy:
      matrix:
        publish-packages: [
          com.github.asus4.onnxruntime,
          com.github.asus4.onnxruntime.unity,
          com.github.asus4.onnxruntime.linux-x64-gpu,
          com.github.asus4.onnxruntime.win-x64-gpu
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: ./download-binaries.sh v1.16.3
      # Publish all packages in matrix
      - run: npm publish
        working-directory: ${{ matrix.publish-packages }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
