name: Publish UPM packages
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
      - name: Download binaries
        run: ./scripts/download-binaries.sh v1.16.3
      - name: Publish all packages
        run: |
          cp README.md com.github.asus4.*
          cd ${{ github.workspace }}/com.github.asus4.onnxruntime
          npm publish
          cd ${{ github.workspace }}/com.github.asus4.onnxruntime.unity
          npm publish
          cd ${{ github.workspace }}/com.github.asus4.onnxruntime.linux-x64-gpu
          npm publish
          cd ${{ github.workspace }}/com.github.asus4.onnxruntime.win-x64-gpu
          npm publish
          cd ${{ github.workspace }}/com.github.asus4.onnxruntime.extensions
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
